name: 'Pipeline 04/07/26'

on:
  # Habilita botão na interface web para acionar manualmente a pipeline
  workflow_dispatch:

  jobs:
    integração:
      name: 'integração'
      runs-on: ubuntu-latest
      steps:
        # Equivalente a git clone
        - uses: actions/checkout@v4
        - name: 'Instalação de dependencias'
          run: pip install -r requirements.txt
        - name: 'Teste unitários'
          run: pytest